version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ASSISTANT_ID=${ASSISTANT_ID}
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
